export function generateEmailHtml(data: {
  reportType: 'Weekly' | 'Monthly';
  revenueData: any[];
  teacherData: any[];
}) {
  const { reportType, revenueData, teacherData } = data;
  
  // Calculate total revenue and bookings from data
  const totalRevenue = revenueData.reduce((acc, row) => acc + row.total_revenue, 0);
  const totalBookings = teacherData.reduce((acc, row) => acc + row.total_bookings, 0);

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; }
    .container { max-width: 600px; margin: 20px auto; padding: 20px; border: 1px solid #eee; border-radius: 8px; }
    .header { background: #000; color: #fff; padding: 30px 20px; text-align: center; border-radius: 6px 6px 0 0; }
    .header h1 { margin: 0; font-size: 28px; letter-spacing: 1px; }
    .stat-grid { display: flex; justify-content: space-around; gap: 20px; margin: 30px 0; }
    .stat-card { flex: 1; background: #f9f9f9; padding: 20px; border-radius: 12px; text-align: center; border: 1px solid #f0f0f0; }
    .stat-value { font-size: 24px; font-weight: bold; color: #000; margin-bottom: 5px; }
    .stat-label { font-size: 14px; color: #666; }
    .section-title { border-left: 4px solid #000; padding-left: 10px; margin: 40px 0 20px; font-size: 18px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { text-align: left; padding: 15px; border-bottom: 1px solid #eee; }
    th { background: #fafafa; font-size: 13px; text-transform: uppercase; letter-spacing: 0.5px; color: #888; }
    td { font-size: 15px; }
    .bilingual { font-size: 12px; color: #999; display: block; margin-top: 2px; font-weight: normal; }
    .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #bbb; border-top: 1px solid #eee; padding-top: 20px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${reportType} Performance Report</h1>
      <span style="color: #888; font-size: 14px; margin-top: 5px; display: block;">${reportType === 'Weekly' ? '周报' : '月报'} 表现报告</span>
    </div>
    
    <div class="stat-grid">
      <div class="stat-card">
        <div class="stat-value">¥${totalRevenue.toLocaleString()}</div>
        <div class="stat-label">Total Revenue <span class="bilingual">总收入</span></div>
      </div>
      <div class="stat-card">
        <div class="stat-value">${totalBookings}</div>
        <div class="stat-label">Total Bookings <span class="bilingual">总预订量</span></div>
      </div>
    </div>

    <div class="section-title">
      Teacher Performance <span class="bilingual">老师表现</span>
    </div>
    <table>
      <thead>
        <tr>
          <th>Teacher <span class="bilingual">老师</span></th>
          <th>Bookings <span class="bilingual">预订</span></th>
          <th>Fill Rate <span class="bilingual">上座率</span></th>
        </tr>
      </thead>
      <tbody>
        ${teacherData.map(t => `
          <tr>
            <td style="font-weight: 500;">${t.teacher_name}</td>
            <td>${t.total_bookings}</td>
            <td><span style="color: ${t.avg_fill_rate >= 80 ? '#22c55e' : t.avg_fill_rate >= 50 ? '#f59e0b' : '#ef4444'}">${t.avg_fill_rate.toFixed(1)}%</span></td>
          </tr>
        `).join('')}
      </tbody>
    </table>

    <div class="footer">
      Generated by Dance Studio Management System<br>
      © ${new Date().getFullYear()} Dance Studio
    </div>
  </div>
</body>
</html>
  `;
}
